### ISSUE TITLE
Win 11

### ISSUE THREAD

**Issue by Arctic4161** [pathartl/BananaSplit#27] opened 2022-05-16 15:34 UTC
Appears to run on win 11 now but when you select a file it states detecting black frames and then just closes. Not sure why. The file format I am using is MP4
Codec for file is H.264 - MPEG-4 AVC. Not sure if that matters or not.  Seems to work on H.265 though which is odd.
It appears the GUI closes but FFmpeg is still open in the background. I've converted this file to different formats and still crashes the GUI.

Works with some files and crashes with others. File size is too large to attach here

**Comment by Arctic4161** [comment] 2022-05-16 15:44
Codec for file is H.264 - MPEG-4 AVC. Not sure if that matters or not.  Seems to work on H.265 though which is odd.

**Comment by Arctic4161** [comment] 2022-05-18 19:21
GUI crashes when it gets to the Parsed blackframe messages in the log. But only on some files. Not sure why

**Comment by ricardosabino** [comment] 2022-05-22 04:05
Not sure if it's the same or not but I've experienced crashes before when parsing black frames and it was due to ffmpeg not handling a specific file format. Unfortunately I don't remember the file format. My workaround was to convert the affected files to another format using vlc.

**Comment by Arctic4161** [comment] 2022-05-22 15:43
I've converted the files that crash with vlc and handbrake to h.265, h.264.
Edited with windows to save and covert. Same issue. Changed the name of the
files. At this point I have no idea what the issue is tbh.

**Comment by ricardosabino** [comment] 2022-05-22 16:14
If the file is not too big maybe you can give it to me via wetransfer.com or some other mean and I'll try to check when I have time. I don't have windows 11 yet so not sure if this is happening on win 10 but if it is then I might be able to fix if this is an issue with the code itself and not ffmpeg or any other dependency.

**Comment by Arctic4161** [comment] 2022-05-22 21:49
Hey ricardo, I appreciate it. Here is the link, https://we.tl/t-XeZ0yTGrgJ
If it fails for you, you may at least see the error message. I don't have experience in C

**Comment by ricardosabino** [comment] 2022-05-23 06:42
I wasn't able to reproduce the issue.
![image](https://user-images.githubusercontent.com/2054201/169758922-d5db2d18-f276-4867-a145-d9f75bf31c8e.png)

Do you have any settings changed? Do you see any error in the logs?

**Comment by Arctic4161** [comment] 2022-05-23 13:02
No nothing, has to be something with win 11. Everything's default, Gui
crashes and ffmpeg runs in the background. Anyway you can package one to
write a log of the gui? crash log or something.

**Comment by Arctic4161** [comment] 2022-05-28 18:29
Tested on Win10 the gui still crashes. Not sure whats going on tbh. I have added it as an exception to my antivirius. Ran it as admin. Still crashes. Bananasplit release 3.0.0 doesn't crash for me on win10

**Comment by ricardosabino** [comment] 2022-06-24 08:06
I'm sorry for the delay. I'm not sure why you're getting a crash. I'll try to add some debug logs and upload a temp build somewhere where you can download.

**Comment by ricardosabino** [comment] 2022-06-30 03:11
@Arctic4161 let me know if you can try this version: [https://we.tl/t-WyKC0DdP4p](https://we.tl/t-WyKC0DdP4p)
It should show a message when it crashes.

**Comment by pathartl** [comment] 2022-07-20 01:39
I was able to replicate the issue on Windows 11. A new build has been pushed (v3.2.1). Please update and try again. Closing for now...

**Closed as completed by pathartl** 2022-07-20 01:39 UTC
